song_list = {
    'Singles': {
        1: 'All About Us',
        2: 'Humbug',
        3: 'Kiss Me Babe, It\'s Christmas Time',
        4: 'Light of Christmas',
        5: 'Peppermint Winter', 
        6: 'The First Noel',
        7: 'Lonely Lullaby',
        8: 'Waving Through a Window',
        9: 'Eternity',
        10: 'To the Sky',
        11: 'Youtopia',
        12: 'In the Air',
        13: 'Boston',
        14: 'Car Trouble',
        15: 'Forever & Always',
        16: 'Let The Light In',
        17: 'Up To The Cloud',
        18: 'Cactus in the Valley',
        19: 'Alive',
        20: 'Listen to What the Man Said',
        21: 'Shine Your Way',
        22: 'Live It Up',
        23: 'When Can I See You Again?',
        24: 'Wonderfilled'
    },
    'All Things Bright and Beautiful': {
        1: 'The Real World',
        2: 'Deer in the Headlights',
        3: 'Angels',
        4: 'Dreams Don\'t Turn to Dust',
        5: 'Honey and the Bee',
        6: 'Kamikaze',
        7: 'January 28, 1986',
        8: 'Galaxies',
        9: 'Hospital Flowers',
        10: 'Alligator Sky',
        11: 'The Yacht Club',
        12: 'Plant Life',
        13: 'How I Became the Sea',
        14: 'Shy Violet',
    },
    'Cinematic': {
        1: 'All My Friends',
        2: 'Always',
        3: 'Be Brave',
        4: 'Cinematic',
        5: 'Cloud Nine',
        6: 'Fiji Water',
        7: 'Firebird',
        8: 'House Wren',
        9: 'Lucid Dream',
        10: 'Madeline Island',
        11: 'Montana',
        12: 'New York City',
        13: 'Not All Heroes Wear Capes',
        14: 'Winners Never Quit',
        15: 'The 5th of July'
    },
    'Coco Moon': {
        1: 'Adam, Check Please',
        2: 'Dinosaur Park',
        3: 'Field Notes',
        4: 'Kelly Time',
        5: 'Learn How to Surf',
        6: 'The Meadow Lark',
        7: 'My Muse',
        8: 'Sons of Thunder',
        9: 'The Tornado',
        10: 'Under the Circus Lights',
        11: 'Vitamin Sea',
    },
    'Maybe I\'m Dreaming': {
        1: 'Air Traffic',
        2: 'Dear Vienna',
        3: 'Early Birdie',
        4: 'I\'ll Meet You There',
        5: 'On the Wing',
        6: 'Rainbow Veins',
        7: 'The Saltwater Room',
        8: 'Sky Diver',
        9: 'Super Honeymoon',
        10: 'The Technicolor Phase',
        11: 'West Coast Friendship',
    },
    'Mobile Orchestra': {
        1: 'Back Home',
        2: 'Bird With a Broken Wing',
        3: 'Can\'t Live Without You',
        4: 'I Found Love',
        5: 'My Everything',
        6: 'This Isn\'t the End',
        7: 'Thunderstruck',
        8: 'Unbelievable',
        9: 'Verge',
        10: 'You\'re Not Alone',
        11: 'Mobile Orchestra',
        12: 'Tokyo',
        13: 'Up All Night',      
    },
    'Ocean Eyes': {
        1: 'Cave In',
        2: 'Dental Care',
        3: 'Fireflies',
        4: 'Hello Seattle',
        5: 'Meteor Shower',
        6: 'On the Wing',
        7: 'The Saltwater Room',
        8: 'Tidal Wave',
        9: 'The Tip of the Iceberg',
        10: 'Umbrella Beach',
        11: 'Vanilla Twilight',
        12: 'Butterfly Wings',
        13: 'Hot Air Balloon',
        14: 'If My Heart Was a House',
        15: 'Rugs From Me to You',
        16: 'Strawberry Avalanche',
        17: 'Sunburn'
    },
    'Of June': {
        1: 'The Airway',
        2: 'Captains and Cruise Ships',
        3: 'Designer Skyline',
        4: 'Fuzzy Blue Lights',
        5: 'Hello Seattle',
        6: 'Panda Bear',
        7: 'Swimming in Miami',
    },
    'Shooting Star': {
        1: 'Dementia',
        2: 'Gold',
        3: 'Shooting Star',
        4: 'Take It All Away',
    },
        'The Midsummer Station': {
        1: 'Dementia',
        2: 'Dreams and Disasters',
        3: 'Embers',
        4: 'Gold',
        5: 'Good Time',
        6: 'I\'m Coming After You',
        7: 'Metropolis',
        8: 'Shooting Star',
        9: 'Silhouette',
        10: 'Speed of Love',
        11: 'Take It All Away',
        12: 'Hey Anna',
        13: 'I Hope You Think of Me',
        14: 'Bombshell Blonde',
        15: 'Top of the World'
    },
    'Ultraviolet': {
        1: 'Beautiful Times',
        2: 'This Isn\'t the End',
        3: 'Up All Night',
        4: 'Wolf Bite'
    }
}